#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# panel
~/.config/polybar/launch.sh &

#xrandr shit test
/home/vivian/.screenlayout/default.sh

# Set some bsp specific stuff
bspc monitor eDP1 -d 一 二 三 四 五
bspc monitor HDMI2 -d 六 七 八 九 十

bspc config window_gap 12
bspc config border_width 5

# "Window Fullscreen"
# bspc config ignore_ewmh_fullscreen all

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Wndow rules
bspc rule -a MuPDF state=floating
bspc rule -a firefox desktop=^3
bspc rule -a discord desktop=^2
bspc rule -a mpv desktop=^8
bspc rule -a URxvt state=floating

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
